### ISSUE TITLE
please add a note that queries & qrels were updated

### ISSUE THREAD

**Issue by guidozuc** [grill-lab/DL-Hard#2]
Hi guys
many thanks for this great resource.

One note. Previous releases were incomplete, with query file containing 49 queries and passage level qrels containing 47 queries.
I have noted that this now has been fixed and the new files contain 50 queries. You may want to add a note at the top of the README to warn people as someone may have started using this resources (like we did) but may have not noted the inconsistency.

**Comment by guidozuc** [comment]
A further observation. In the README you say you consider e.g. the 2019 DL queries; You mention there are 200 queries, which is correct, but then say there are 50 assessed queries. However, in the official TREC DL 2019 qrels, there are only 43 queries (though I do recognised 50 topics may have been assessed and 7 removed from qrels because too less relevant documents). Similarly, in 2020 there were 54 judged queries in the qrels. You may want to change/clarify this, to avoid confusion.

**Comment by iain-mackie** [comment]
Thanks @guidozuc for the very insightful comments - I'll update the README to make this more explicit and avoid confusion!

**Comment by iain-mackie** [comment]
I've added a 'Change Log' section to the README with dated major changes to help historic users.

**Comment by iain-mackie** [comment]
I updated the graphic within the README to have explicit document/passage NIST vs. new judgment breakdowns. Hopefully this will avoid any confusion. I'll also update the SIGIR paper to make this explicit. Thanks again @guidozuc for the feedback!
