### ISSUE TITLE
Any idea when the dense annotations for the 25 new queries will be released?

### ISSUE THREAD

**Issue by rodrigonogueira4** [grill-lab/DL-Hard#3]
I'm asking based on this item in the README.md:
- _Non-NIST judged queries only judge top 10 docs from the QnA dataset (i.e. judgments sparse). Thus, creating deeper judgments._

**Comment by iain-mackie** [comment]
Hi Rodrigo, Yes, we plan to release these in the coming months. But we have some work still to do and don't have a concrete release date imminent. Will keep you posted when these become available!

**Comment by rodrigonogueira4** [comment]
Great, thanks!
